name: Deploy
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              uses: actions/setup-node@v2
              with:
                  node-version: 16.14.0
            - name: Install dependencies
              run: |
                  npm i -g yarn
                  yarn
            - name: Build
              run: |
                  yarn build
                  mv build auto-build
            - name: Deploy
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  # key: ${{secrets.KEY}}
                  port: ${{ secrets.PORT }}
                  source: "./auto-build"
                  target: ${{secrets.TARGET}}
                  rm: true

            - name: extract files
              uses: appleboy/ssh-action@master
              with: 
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    password: ${{ secrets.PASSWORD }}
                    port: ${{ secrets.PORT }}
                    script: |
                        cd ${{ secrets.TARGET }}
                        mv ./auto-build/* ./
                        rm -rf ./auto-build
